# 应用服务器
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 15000  # 最大允许的连接数
    accept-count: 2000      # 最大排队等待数
    threads:
      max: 800
  port: 40002
  shutdown: graceful

# 数据库
spring:
  main:
    allow-bean-definition-overriding: true

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:com/zc/framework/**/mapper/xml/*,classpath*:com/zc/**/mapper/xml/*
  configuration:
    cache-enabled: true

# swagger配置
springdoc:
  packages-to-exclude:
    - com.zc.kpi.biz.controller.feign
knife4j:
  enable: true
  setting:
    language: zh_cn
zc:
  framework:
    feign:
      system: kpi-base
